name: Latest medium articles
on:
  schedule:
    - cron: '0 0 * * MON' # Runs every Monday at 12:00 AM
  workflow_dispatch:
jobs:
  update-readme-with-medium-articles:
    name: Update README with the latest medium articles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@klshriharsha"